apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-chart.fullname" . }}-secrets
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.postgresql.enabled }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.apiKey }}
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-chart.fullname" . }}-docker-secret
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.imagePullSecrets.dockerConfig | b64enc | quote }}
